runtime: php
env: flex
#application: toylibrary-191807
runtime_config:
  document_root: .

#[START env]
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    MYSQL_USER: root
    MYSQL_PASSWORD: clouddb
    MYSQL_DSN: mysql:unix_socket=/cloudsql/toylibrary-191807:asia-northeast1:cloudmysql1;dbname=toy
#[END env]

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "toylibrary-191807:asia-northeast1:cloudmysql1"
#[END cloudsql_settings]